import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import CustomCursor from "@/components/CustomCursor";
import PageTransition from "@/components/PageTransition";



import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false


const filson = localFont({
  src: [
    {
      path: './fonts/FilsonProBook.otf',
      weight: '300',
      style: 'normal'
    },
    {
      path: './fonts/FilsonProRegular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/FilsonProMedium.otf',
      weight: '600',
      style: 'normal'
    },
    {
      path: './fonts/FilsonProBold.otf',
      weight: '700',
      style: 'normal'
    }
  ],
  variable: '--font-filson'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`overflow-x-hidden h-full antialiased ${filson.variable}`}
    >
      <body className={`${filson.className} overflow-x-hidden`}>
    
       <CustomCursor />
        <Header />
        
        {children}
       
        <Footer />
       
      </body>
    </html>
  );
}